### ISSUE TITLE
Re-write?

### ISSUE THREAD

**Issue by theguyfortech** [theguyfortech/TTGProtect#3]
TTGProtect is getting very slow with each passing command. I think the bot should be completely re-written and built again from the ground up better and more awesome!

## What does this mean for you?
First, a lot of downtime. I might make a public "Dev" version of TTGProtect, but who knows?
Second, You won't be able to use TTGProtect for quite a long time. _Note: The bot might have a few minutes online due to me testing_

What do you guys think?

**Comment by StupidDan** [comment]
# TTGProtect to-do list
#### This is a small list of things that I personally think needs to be improved in the bot.

* Command handler of some sort.
* More unique commands like slots, something to engage members and make the bot more unique and more fun to use.
* A better logo, it's abit bland and is probably from Google Images.
* A better designed help menu, it's abit messy and doesn't look very good at the moment.

Anyway, that's all for now, might be added to in the future. :thumbsup:

**Comment by theguyfortech** [comment]
@StupidDan Yeah, for the re-write I was going to make a Command Handler/

This is starting to sound like the GAwesomeBot problem lol :P

**Comment by StupidDan** [comment]
Yeah lmao

**Comment by theguyfortech** [comment]
So, this is decided! 👍 

I'll be starting the re-write soon! :)

**Comment by StupidDan** [comment]
Alright, good luck! 😄
